- name: Install Nodejs
  yum: 
    name: nodejs
    state: present
  become: yes
  become_user: root
  become_method: sudo

- name: Install frontend npm dependencies
  shell: cd ~/mysite/frontend && npm install --legacy-peer-deps

- name: Build Production React
  shell: cd ~/mysite/frontend && npm run build 
  